project/basic/urls.py
from django.urls import path

from .views import (
    HomeView,
    StaticPageView,
    EventsView,
    EventsPageView,
    YouTubeVideoAlbumsView,
    YouTubeVideoAlbumDetailView,
    InterestingView,
    InterestingDetailView,
    LibraryView,
    LibraryBooksView,
    ContactView,
    ReviewListView,
    YouTubeAudioAlbumsView,
    YouTubeVideoInterestingAlbumsView,
    YouTubeVideoCognitiveAlbumsView,
    YouTubeAudioAlbumDetailView
)

app_name = 'basic'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('events/', EventsView.as_view(), name='events'),
    path('events/<slug:slug>/', EventsPageView.as_view(), name='events_page'),
    path('interesting/', InterestingView.as_view(), name='interesting'),
    path('interesting/<slug:slug>/', InterestingDetailView.as_view(), name='interesting_detail'),
    path('videos/', YouTubeVideoAlbumsView.as_view(), name='video_albums'),
    path('videos/<int:pk>/', YouTubeVideoAlbumDetailView.as_view(), name='video_album_detail'),
    path('audios/', YouTubeAudioAlbumsView.as_view(), name='audio_albums'),
    path('videos-interesting/', YouTubeVideoInterestingAlbumsView.as_view(), name='videos_interesting_albums'),
    path('videos-cognitive/', YouTubeVideoCognitiveAlbumsView.as_view(), name='videos_cognitive_albums'),
    path('library/', LibraryView.as_view(), name='library'),
    path('library/<int:pk>/', LibraryBooksView.as_view(), name='library_books'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('reviews/', ReviewListView.as_view(), name='reviews'),
    path('<slug:slug>/', StaticPageView.as_view(), name='static_page')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.staticfiles import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('', RedirectView.as_view(url='/ru/')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('<slug:lang>/', include('basic.urls', namespace='basic')),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', views.serve),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/templates/parts/banner.html
<section class="hero-area bg-1 text-center overly">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="content-block">
                    <h1>Саморазвитие и Самопознание</h1>
                    <p class="text-right">
                        "Относиться к самим себе с изобильной заботой и вниманием - это первый шаг к жизни в Изобилии"
                    </p>
                    <p class="text-right">Альмин</p>
                </div>
            </div>
        </div>
    </div>
</section>

project/templates/parts/breadcrumbs.html
<ul class="breadcrumb">
    {% for path in paths %}
        <li>
            <a href="{{ path.path }}">
                {{ path.title }}
            </a>
        </li>
    {% endfor %}

</ul>

project/templates/parts/footer.html
{% load static i18n %}
<footer class="footer-bottom">
    <!-- Container Start -->
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-12">
          <!-- Copyright -->
          <div class="copyright">
            <p>
                {% trans 'Copyright' %} © {{ now|date:'Y' }}. {% trans 'All Rights Reserved' %}
            </p>
          </div>
        </div>
        <div class="col-sm-6 col-12">
          <!-- Social Icons -->
          <ul class="social-media-icons text-right">
              <li>
                  <a  target="_blank" class="" href="http://fb.me/SamorazvitieISamopoznanieMushtariyYuldasheva">
                    <span class="fa fa-facebook"></span>
                    Facebook
                  </a>
              </li>
              <li>
                  <a  target="_blank"  href="https://telegram.me/SamorazvitieSamopoznanieMushtari">
                      <span class="fa fa-telegram"></span>
                      Telegram
                  </a>
              </li>
              <li>
                  <a  target="_blank"  href="https://www.youtube.com/channel/UCwrLhO9wRFiIrPtx3MK5SnQ">
                      <span class="fa fa-youtube"></span>
                      Youtube
                  </a>
              </li>
              <li>
                  <a target="_blank" href="skype:larafan83?call">
                      <span class="fa fa-skype"></span>
                      Skype
                  </a>
              </li>
            </ul>
        </div>
      </div>
    </div>
    <!-- Container End -->
    <div class="top-to">
      <a id="top" class="" href=""><i class="fa fa-angle-up"></i></a>
    </div>
</footer>
<div class="top-to">
  <a id="top" href="#"><i class="fa fa-angle-up"></i></a>
</div>

project/templates/parts/header.html
{% load static i18n %}
{%  get_current_language as LANG_CODE %}
<section>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<nav class="navbar navbar-expand-lg  navigation">
					<a class="navbar-brand" href="{% url 'basic:home' lang=LANG_CODE %}">
						<img class="header-logo" src="{{ site_logo }}" alt="">
					</a>
					<button class="navbar-toggler open_menu" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="menu_item_liner"></span>
                        <span class="menu_item_liner"></span>
                        <span class="menu_item_liner"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav ml-auto main-nav ">
                            {% for menu_item in menu_items %}
                                {% if menu_item.get_children %}
                                    <li class="nav-item dropdown dropdown-slide">
                                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            {{ menu_item.title }}
                                            <span><i class="fa fa-angle-down"></i></span>
                                        </a>
                                        <!-- Dropdown list -->
                                        <div class="dropdown-menu dropdown-menu-right">
                                            {% for child in menu_item.get_children %}
                                                <a class="dropdown-item {% if request.path == child.get_absolute_url %}active{% endif %}" href="{{ child.get_absolute_url }}">
                                                    {{ child.title }}
                                                </a>
                                            {% endfor %}

                                        </div>
                                    </li>
                                {% else %}
                                    <li class="nav-item {% if request.path == menu_item.get_absolute_url %}active{% endif %}" >
                                        <a class="nav-link " href="{{ menu_item.get_absolute_url }}">
                                            {{ menu_item.title }}
                                        </a>
                                    </li>
                                {% endif %}

                            {% endfor %}
						</ul>
					</div>
				</nav>
			</div>
		</div>
	</div>
</section>

project/templates/parts/pagination.html
{% if is_paginated %}
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}#" aria-label="Prev">
                    <span aria-hidden="true"><i class="fa fa-angle-left"></i></span>
                    <span class="sr-only">Prev</span>
                </a>
            </li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true"><i class="fa fa-angle-right"></i></span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endif %}