project/basic/urls.py
from django.urls import path

from .views import (
    HomeView,
    StaticPageView,
    EventsView,
    EventsPageView,
    YouTubeVideoAlbumsView,
    YouTubeVideoAlbumDetailView,
    InterestingView,
    InterestingDetailView,
    LibraryView,
    LibraryBooksView,
    ContactView,
    ReviewListView,
    YouTubeAudioAlbumsView,
    YouTubeVideoInterestingAlbumsView,
    YouTubeVideoCognitiveAlbumsView,
    YouTubeAudioAlbumDetailView
)

app_name = 'basic'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('events/', EventsView.as_view(), name='events'),
    path('events/<slug:slug>/', EventsPageView.as_view(), name='events_page'),
    path('interesting/', InterestingView.as_view(), name='interesting'),
    path('interesting/<slug:slug>/', InterestingDetailView.as_view(), name='interesting_detail'),
    path('videos/', YouTubeVideoAlbumsView.as_view(), name='video_albums'),
    path('videos/<int:pk>/', YouTubeVideoAlbumDetailView.as_view(), name='video_album_detail'),
    path('audios/', YouTubeAudioAlbumsView.as_view(), name='audio_albums'),
    path('videos-interesting/', YouTubeVideoInterestingAlbumsView.as_view(), name='videos_interesting_albums'),
    path('videos-cognitive/', YouTubeVideoCognitiveAlbumsView.as_view(), name='videos_cognitive_albums'),
    path('library/', LibraryView.as_view(), name='library'),
    path('library/<int:pk>/', LibraryBooksView.as_view(), name='library_books'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('reviews/', ReviewListView.as_view(), name='reviews'),
    path('<slug:slug>/', StaticPageView.as_view(), name='static_page')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.staticfiles import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('', RedirectView.as_view(url='/ru/')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('<slug:lang>/', include('basic.urls', namespace='basic')),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', views.serve),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/templates/pages/contact.html
{% extends 'base.html' %}
{% load static i18n widget_tweaks %}


{% block content %}
    {{ header }}
    {{ banner }}
    <section class="inner-section">
        <!-- Container Start -->
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title">
                        <h2>{{ page_title }}</h2>
                    </div>
                </div>
                {% for message in messages %}
                    <div class="alert alert-success full-width text-center">
                        {{ message }}
                    </div>
                {% endfor %}

                <div class="col-md-12">
                    <div class="text-center text-primary info-text-lg">
                        Чтобы попасть на семинар-тренинг просим Вас пройти регистрацию у нашего администратора-организатора.
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for hidden_field in form.hidden_fields %}
                            {{ hidden_field }}
                        {% endfor %}

                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                                {% for error in form.non_field_errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                        {% for field in form.visible_fields %}
                            <div class="form-group">
                                {{ field.label_tag }}
                                {% if form.is_bound %}
                                    {% if field.errors %}
                                        {% render_field field class="form-control is-invalid" %}
                                        {% for error in field.errors %}
                                            <div class="invalid-feedback">
                                                {{ error }}
                                            </div>
                                        {% endfor %}
                                    {% else %}
                                        {% render_field field class="form-control is-valid" %}
                                    {% endif %}
                                {% else %}
                                    {% render_field field class="form-control" %}
                                {% endif %}
                                {% if field.help_text %}
                                    <small class="form-text text-muted">{{ field.help_text }}</small>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary" >{% trans 'Submit' %}</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-7">
                    <div class="phone">
                        <b style="vertical-align: top;">{% trans 'Tel' %}.:</b> &nbsp;&nbsp;&nbsp;
                        <ul class="" style="display: inline-block; list-style-type: decimal;">
                            <li class="">Офис: +998 91 776 0202;</li>
                            <li class="">Муштарий: +998 90 946 16 36;</li>
                            <li class="">Лола: +998 97 347 20 65.</li>
                        </ul>
                    </div>
                    <div class="email">
                        <b>{% trans 'Email' %}</b>:
                        <a href="mailto:samopoznanie.uz@mail.ru">samopoznanie.uz@mail.ru</a>,
                        <a href="mailto:flagman8383@mail.ru">flagman8383@mail.ru</a>
                    </div>
                    <div class="address">
                        <b>{% trans 'Address' %}</b>:
                        <span id="address_content">
                            г. Ташкент, Чиланзарский р-он, улица Новза (Комила Ярматова),
                        14 дом, здание Бизнес-центра, 4 этаж, кабинет 4-11, ориентир - кафе Анхор.
                        </span>
                    </div>
                    <br>
                    <div id="map" style="width: 100%; height: 400px;"></div>
                </div>
            </div>
        </div>
    </section>
    {{ footer }}
{% endblock %}
{% block js %}

  <script src="https://maps.google.com/maps/api/js?libraries=places&key=AIzaSyCd2b6Uypec_SgphkHeF4Pe4phMy51BSTQ"></script>
    <script>
        window.marker = null;

function initialize() {
    var map;

    var nottingham = new google.maps.LatLng(41.300108, 69.240041);

    var style = [ {} ];

    var mapOptions = {
        // SET THE CENTER
        center: nottingham,

        // SET THE MAP STYLE & ZOOM LEVEL
        mapTypeId: google.maps.MapTypeId.ROADMAP,

        // SET THE BACKGROUND COLOUR
        backgroundColor:"#000",

        // REMOVE ALL THE CONTROLS EXCEPT ZOOM
        zoom: 14,
        panControl:false,
        zoomControl:true,
        mapTypeControl:false,
        scaleControl:false,
        streetViewControl:false,
        overviewMapControl:false,
        zoomControlOptions: {
            style:google.maps.ZoomControlStyle.LARGE
        }

    }
    map = new google.maps.Map(document.getElementById('map'), mapOptions);

    // SET THE MAP TYPE
    var mapType = new google.maps.StyledMapType(style, {name:"Grayscale"});
    map.mapTypes.set('grey', mapType);
    map.setMapTypeId('grey');

    //CREATE A CUSTOM PIN ICON
    var marker_image = "{% static 'images/marker.png' %}";
    var pinIcon = new google.maps.MarkerImage(marker_image,null,null, null,new google.maps.Size(74, 73));

    marker = new google.maps.Marker({
        position: nottingham,
        map: map,
        icon: pinIcon,
        title: 'eventre'
    });
    var content = $('#address_content').html();
    var infowindow = new google.maps.InfoWindow({
        content: "<div style='width: 300px'>" + content +"</div>"
    });
    infowindow.open(map, marker);

}

google.maps.event.addDomListener(window, 'load', initialize);
    </script>
{% endblock %}

project/templates/pages/events.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    {{ header }}
    {{ banner }}
    <section class="inner-section">
        <!-- Container Start -->
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title">
                        <h2>{{ page_title }}</h2>
                    </div>
                </div>
                {% for object in object_list %}
                    <div class="col-md-6">
                        <article>
                            <!-- Post Image -->
                            <div class="image">
                                <img src="{% static 'images/blog/post-1.jpg' %}" alt="article-01">
                            </div>
                            <!-- Post Title -->
                            <h3><a href="{{ object.get_absolute_url }}" class="">{{ object.title }}</a></h3>
                            <ul class="list-inline">
                                <li class="list-inline-item">{{ object.created_at|date:'F d, Y' }}</li>
                            </ul>
                            <!-- Post Description -->
                            <p class="">
                                {{ object.body|truncatewords_html:40|safe }}
                            </p>
                            <!-- Read more button -->
                            <a href="{{ object.get_absolute_url }}" class="btn btn-transparent">{% trans 'Read More' %}</a>
                        </article>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="container">
            <div class="row">
                {% include 'parts/pagination.html' %}
            </div>
        </div>
    </section>

    {{ footer }}
{% endblock %}

project/templates/pages/events_page.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    {{ header }}
    {{ banner }}
    <section class="inner-section">
        <!-- Container Start -->
        <div class="container">
            <div class="row">
                <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-0">
                    <article class="single-post">
                        <h3>{{ object.title }}</h3>
                        <ul class="list-inline">
                            <li class="list-inline-item">{{ object.created_at|date:'F d, Y' }}</li>
                        </ul>
                        <img src="{% static 'images/blog/post-4.jpg' %}" alt="article-01">
                        <p>
                            {{ object.body|safe }}
                        </p>
                        <ul class="social-circle-icons list-inline">
                            <li class="list-inline-item text-center"><a class="fa fa-facebook" href=""></a></li>
                            <li class="list-inline-item text-center"><a class="fa fa-twitter" href=""></a></li>
                            <li class="list-inline-item text-center"><a class="fa fa-google-plus" href=""></a></li>
                            <li class="list-inline-item text-center"><a class="fa fa-pinterest-p" href=""></a></li>
                            <li class="list-inline-item text-center"><a class="fa fa-linkedin" href=""></a></li>
                        </ul>
                    </article>
                    <div class="block comment">
                        <h4>Leave A Comment</h4>
                        <form action="#">
                            <!-- Message -->
                            <div class="form-group mb-30">
                                <label for="message">Message</label>
                                <textarea class="form-control" id="message" rows="8"></textarea>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-6">
                                    <!-- Name -->
                                    <div class="form-group mb-30">
                                        <label for="name">Name</label>
                                        <input type="text" class="form-control" id="name">
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6">
                                    <!-- Email -->
                                    <div class="form-group mb-30">
                                        <label for="email">Email</label>
                                        <input type="email" class="form-control" id="email">
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-transparent">Leave Comment</button>
                        </form>
                    </div>
                </div>
                <div class="col-md-10 offset-md-1 col-lg-4 offset-lg-0">
                    <div class="sidebar">
                        <div class="widget category">
						<!-- Widget Header -->
                            <h5 class="widget-header">Другие</h5>
                            <ul class="category-list">
                                {% for item in items %}
                                    <li><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {{ footer }}
{% endblock %}

project/templates/pages/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{{ header }}
{{ banner }}

<section class=" section">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-12">
				<!-- Section title -->
				<div class="section-title">
					<h2>О нас</h2>
				</div>
				<div class="row">
					<div class="text-justify">
                        Дорогие Друзья! Добро пожаловать на наш  медиа TELEGRAM-канал по ссылке https://t.me/mediasamorazvitiesamopoznanie. Видео и аудио файлы, записанные на наших семинарах-тренингах, авторские статьи, авторские практики Муштарий Юлдашевой и многое другое интересное и полезное  в свободном доступе для скачивания на  нашем канале.
                    </div>
				</div>
                <br>
                <div class="row">
                    <div class="col-md-6" style="padding: 0;">
                        <h4>ВНИМАНИЕ!!! НОВОСТЬ! НОВОСТЬ! НОВОСТЬ!</h4>
                        Дорогие Искатели! Муштарий Юлдашева приглашает вас на свой профессиональный курс! Курс предназначен только для будущих психологов и тех, кто уже практикует в этой сфере. Курс будет состоять из трех модулей. Первый модуль стартует 4 сентября и продлится один месяц. Обучение будет в основном ориентироваться на практике. Минимум теории и максимум практики! Для проверки и закрепления полученной информации мы будем приглашать  всех желающих поработать с вами, чтобы Вы могли практиковать с реальными людьми и реальными проблемами.
                    </div>
                    <div class="col-md-6" style="padding: 0;">
                        <img src="https://static.wixstatic.com/media/c7735e_0117303d74524fbbb9f38c320961d7bc~mv2_d_1280_1280_s_2.jpg/v1/fill/w_383,h_383,al_c,q_80,usm_0.66_1.00_0.01/c7735e_0117303d74524fbbb9f38c320961d7bc~mv2_d_1280_1280_s_2.webp" alt="">
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-12" style="padding: 0;">
                        Муштарий Юлдашеванинг профессионал курсининг 2 модул иштирокчилари! Табриклаймиз!!!🎊🎉💐🎊🎉💐👏👏👏👏👏👏👏👏👏👏👏ПРОФЕССИОНАЛЬНЫЙ КУРС МУШТАРИЙ ЮЛДАШЕВОЙ 2 модуль - ВЕЛИКИЙ ТРУД И ГЛУБОКИЕ РЕЗУЛЬТАТЫ у каждой участницы! Девушки, вы молодцы! Вы талантливы! Вы сильны! Вы сможете трансформировать мир! ТОЛЬКО ВПЕРЁД!🌟🌟💫💫💫💫💫💫💫💫💫💫💓🌟🌟💓💓💓💓💓не останавливайтесь! двигайтесь, растите и расширяетесь!!!

                    </div>
                    <div class="col-md-12" style="padding: 0;">
                        <iframe class="half_width_iframe" width="50%" height="352" src="https://www.youtube.com/embed/r_Ewi2L1En8" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                        <iframe class="half_width_iframe" width="50%" height="352" src="https://www.youtube.com/embed/ba3BU3Klbm4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                    </div>
                </div>
			</div>
		</div>
	</div>
	<!-- Container End -->
</section>

{{ footer }}
{% endblock %}

project/templates/pages/interesting.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    {{ header }}
    {{ banner }}
    <section class="inner-section">
        <!-- Container Start -->
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title">
                        <h2>{{ page_title }}</h2>
                    </div>
                </div>
                {% for object in object_list %}
                    <div class="col-md-4">
                        <article>
                            <!-- Post Image -->
                            {% if object.image %}
                            <div class="image">
                                <img class="standard_image" src="{{ object.image.url }}" alt="article-01">
                            </div>
                            {% endif %}
                            <!-- Post Title -->
                            <h3><a href="{{ object.get_absolute_url }}" class="">{{ object.title }}</a></h3>
                            <ul class="list-inline">
                                <li class="list-inline-item">{{ object.created_at|date:'F d, Y' }}</li>
                            </ul>
                            <!-- Post Description -->
                            <p class="">
                                {{ object.body|truncatewords_html:15|safe }}
                            </p>
                            <!-- Read more button -->
                            <a href="{{ object.get_absolute_url }}" class="btn btn-primary pull-right">{% trans 'Read More' %}</a>
                        <div class="clearfix"></div>
                        </article>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="container">
            <div class="row">
                {% include 'parts/pagination.html' %}
            </div>
        </div>
    </section>

    {{ footer }}
{% endblock %}

project/templates/pages/library.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    {{ header }}
    {{ banner }}
    <section class="inner-section">
        <!-- Container Start -->
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title">
                        <h2>{{ page_title }}</h2>
                    </div>
                </div>
                {% for object in object_list %}
                    <div class="col-md-4">
                        <article>
                            <!-- Post Image -->
                            {% if object.image %}
                            <div class="image">
                                <a href="{{ object.get_absolute_url }}" class="">
                                    <img class="standard_image" src="{{ object.image.url }}" alt="article-01">
                                </a>
                            </div>
                            {% endif %}
                            <!-- Post Title -->
                            <h3><a href="{{ object.get_absolute_url }}" class="">{{ object.title }}</a></h3>
                            <p class="books-count">
                                {% trans 'Books' %}: {{ object.books.count }} {% trans 'pcs' %}
                            </p>
                        <div class="clearfix"></div>
                        </article>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="container">
            <div class="row">
                {% include 'parts/pagination.html' %}
            </div>
        </div>
    </section>
    {{ footer }}
{% endblock %}

project/templates/pages/library_books.html
{% extends 'base.html' %}
{% load static i18n %}


{% block content %}
    {{ header }}
    {{ banner }}
    <section class="inner-section">
        <!-- Container Start -->
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title">
                        <h2>{{ page_title }}</h2>
                    </div>
                </div>
                <table class="table table-borderless">
                    <thead>
                    <th></th>
                    <th>{% trans 'Title' %}</th>
                    <th>{% trans 'Size' %}</th>
                    <th class="text-center">{% trans 'Download' %}</th>
                    </thead>
                    <tbody>
                        {% for object in object.books.all %}
                            <tr>
                                <td>{{ forloop.counter }}.</td>
                                <td>
                                    <a href="{{ object.file.url }}">
                                        {{ object.title }}
                                    </a>
                                </td>
                                <td>{{ object.file.size|filesizeformat }}</td>
                                <td class="text-center">
                                    <a href="{{ object.file.url }}" class="fa fa-download book-download ">
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="container">
            <div class="row">
                {% include 'parts/pagination.html' %}
            </div>
        </div>
        <div class="container">
            <div class="row pull-right">
                <a href="{% url 'basic:library' lang=current_lang %}" class="btn btn-transparent ">
                    <span class="fa fa-arrow-left"></span>
                    {% trans 'Back to library' %}
                </a>
            </div>
            <div class="clearfix"></div>
        </div>
    </section>
    {{ footer }}
{% endblock %}

project/templates/pages/review_list.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    {{ header }}
    {{ banner }}
    <section class="inner-section">
        <!-- Container Start -->
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title">
                        <h2>{{ page_title }}</h2>
                    </div>
                </div>
                {% for object in object_list %}
                    <div class="col-md-12">
                        <article>
                            <h4>{{ object.author }}</h4>
                            {% if object.file %}
                                <div>

                                    <audio style="width: 100%;" controls src="{{ object.file.url }}"></audio>
                                </div>
                            {% endif %}
                            {{ object.comment|safe }}
                        </article>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="container ">
            <div class="row ">
                {% include 'parts/pagination.html' %}
            </div>
        </div>
    </section>
    {{ footer }}
{% endblock %}

project/templates/pages/static_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {{ header }}
    {{ banner }}
    <section class="inner-section inner-page">
        <!-- Container Start -->
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <!-- Section title -->
                    <div class="section-title">
                        <h2>{{ content.title }}</h2>
                    </div>
                    <div class="row">
                        {{ content.body|safe }}
                    </div>
                </div>
            </div>
        </div>
    </section>

    {{ footer }}
{% endblock %}

project/templates/pages/video_detail.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    {{ header }}
    {{ banner }}
    <section class="inner-section">
        <!-- Container Start -->
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title">
                        <h2>{{ page_title }}</h2>
                    </div>
                </div>
                {% for object in object.videos.all %}
                    <div class="col-md-6">
                        <article>
                            <!-- Post Image -->
                            <div class="image">
                                <iframe width="100%" height="480" src="https://www.youtube.com/embed/{{ object.get_video_id }}" frameborder="0" allow="encrypted-media" allowfullscreen></iframe>
                            </div>
                        </article>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="container">
            <div class="row">
                {% include 'parts/pagination.html' %}
            </div>
        </div>
    </section>

    {{ footer }}
{% endblock %}

project/templates/pages/videos.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    {{ header }}
    {{ banner }}
    <section class="inner-section">
        <!-- Container Start -->
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title">
                        <h2>{{ page_title }}</h2>
                    </div>
                </div>
                {% for object in object_list %}
                    <div class="col-md-6">
                        <article>
                            <!-- Post Image -->
                            <div class="image">
                                <img src="{{ object.videos.first.get_video_image }}" alt="article-01">
                            </div>
                            <!-- Post Title -->
                            <h3><a href="{{ object.get_absolute_url }}" class="">{{ object.title }}</a></h3>
                            <ul class="list-inline">
                                <li class="list-inline-item">{{ object.created_at|date:'F d, Y' }}</li>
                            </ul>
                            <!-- Post Description -->
                            <p class="">
                                {{ object.body|truncatewords_html:40|safe }}
                            </p>
                            <!-- Read more button -->
                            <a href="{{ object.get_absolute_url }}" class="btn btn-transparent">{% trans 'Read More' %}</a>
                        </article>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="container">
            <div class="row">
                {% include 'parts/pagination.html' %}
            </div>
        </div>
    </section>

    {{ footer }}
{% endblock %}